### PR TITLE
Add support for Provider revoked certificates

### PR DESCRIPTION
**Pull request by ghislainbourgeois**
This PR adds support for Provider revoked certificates. An optional field was added to the `Provider` data bag schema to mark a certificate as revoked. The `Requirer` will be able to use this field to generate a `CertificateRevokedEvent`.

The implementation can be found here: https://github.com/canonical/tls-certificates-interface/pull/22

### CODE REVIEW

**Review by gruyaume — APPROVED** [review]

**Comment by ghislainbourgeois** [comment]
@simskij @jnsgruk can you please take a look at this change?

**Review by jnsgruk — APPROVED** [review]
LGTM - for bonus points let's add an example to the schema where this is included?

**Comment by ghislainbourgeois** [comment]
> LGTM - for bonus points let's add an example to the schema where this is included?

@jnsgruk Good point, I added an example to the schema.

**Comment by simskij** [comment]
> > LGTM - for bonus points let's add an example to the schema where this is included?
> 
> @jnsgruk Good point, I added an example to the schema.

Where did this go? Can't see it in the PR.

**Comment by ghislainbourgeois** [comment]
> > > LGTM - for bonus points let's add an example to the schema where this is included?
> > 
> > 
> > @jnsgruk Good point, I added an example to the schema.
> 
> Where did this go? Can't see it in the PR.

My bad, I only did the change on the project implementing this interface. I just pushed the change to this project.

**Pull request merged**
