### PR TITLE
chore: fix failed unit, integration tests json schema check

### PR DESCRIPTION
**Pull request by IronCore864**
Fix failed unit and integration tests due to upgrade to Scenario 7 and fix JSON schema checks (files generated automatically by `tox -e build-json-schemas`).

The scenario version is pinned to 7.0.5, so that future changes won't accidentally break the tests here.

Also fixed version conflicts in tox build-json-schemas.

### CODE REVIEW

**Comment by IronCore864** [comment]
@mmkay Please also take a look at this, it's related to the failed checks in your PR as well.

**Review by tonyandrewmeyer — COMMENTED** [review]
Can we pin pytest-interface-tester to 3.1.0 exactly for now? Other than that, this seems fine as a stop-gap measure, assuming that it doesn't flow on to block charms from upgrading to Scenario 7 as well. If it does, I guess it's still ok as a stop-gap if it only does so in a release, but we'd want to address the underlying problems quickly.

**Comment by IronCore864** [comment]
I pinned Scenario to the latest version 7.0.5 (strictly equal, not greater than, in case future API changes break the CI here).

**Comment by IronCore864** [comment]
Close due to duplication https://github.com/canonical/charm-relation-interfaces/pull/177.

**Pull request closed without merging**
