### PR TITLE
Implementation of the 5G NRF interface

### PR DESCRIPTION
**Pull request by gruyaume**
### Overview
Within 5G, the Network Repository Function (NRF) is responsible for providing information about discovered network function instances. This relation interface describes the expected behavior of any charm claiming to be able to provide or consume NRF information.

### References
- https://www.iplook.com/products/5gc-nrf#:~:text=NRF%2C%20one%20of%20the%20network,discovered)%20to%20another%20NF%20instance.
- https://docs.google.com/document/d/1GDDrwXhICAK0ttBCMYlnZ6TEc2QSnxcR_jKMxMr59pE/edit

### CODE REVIEW

**Comment by gruyaume** [comment]
@PietroPasotti Do you know why the CI is failing? Are we expected to provide json schemas in addition to the pydantic ones?

**Comment by PietroPasotti** [comment]
> @PietroPasotti Do you know why the CI is failing? Are we expected to provide json schemas in addition to the pydantic ones?

Indeed.
image

**Comment by gruyaume** [comment]
> > @PietroPasotti Do you know why the CI is failing? Are we expected to provide json schemas in addition to the pydantic ones?
> 
> Indeed. image

It's strange to have to provide both the pydantic and the json schemas, they contain the same information.

**Comment by PietroPasotti** [comment]
> > > @PietroPasotti Do you know why the CI is failing? Are we expected to provide json schemas in addition to the pydantic ones?
> > 
> > 
> > Indeed. image
> 
> It's strange to have to provide both the pydantic and the json schemas, they contain the same information.

I agree, but it was decided by @simskij and @jnsgruk (see https://github.com/canonical/charm-relation-interfaces/pull/49#issuecomment-1469474761) that this would be the design.
The reasoning is IIRC: for those who'd rather read or use jsonschema (the de-facto portable standard, rather than pydantic), it'd be better to be able to see it in-repo, instead of having to generate it manually or dig through build artifacts to find them.

If you wish to re-open the discussion on that one, fine by me but not here :)

**Review by PietroPasotti — APPROVED** [review]
LGTM

**Comment by gruyaume** [comment]
> > > > @PietroPasotti Do you know why the CI is failing? Are we expected to provide json schemas in addition to the pydantic ones?
> > > 
> > > 
> > > Indeed.
> > 
> > 
> > It's strange to have to provide both the pydantic and the json schemas, they contain the same information.
> 
> I agree, but it was decided by @simskij and @jnsgruk (see [#49 (comment)](https://github.com/canonical/charm-relation-interfaces/pull/49#issuecomment-1469474761)) that this would be the design. The reasoning is IIRC: for those who'd rather read or use jsonschema (the de-facto portable standard, rather than pydantic), it'd be better to be able to see it in-repo, instead of having to generate it manually or dig through build artifacts to find them.
> 
> If you wish to re-open the discussion on that one, fine by me but not here :)

@simskij's comment mentions that we should "have a CI step that generates the json schema", that's not what we have here.

**Review by ghislainbourgeois — APPROVED** [review]

**Comment by simskij** [comment]
> > > > > @PietroPasotti Do you know why the CI is failing? Are we expected to provide json schemas in addition to the pydantic ones?
> > > > 
> > > > 
> > > > Indeed.
> > > 
> > > 
> > > It's strange to have to provide both the pydantic and the json schemas, they contain the same information.
> > 
> > 
> > I agree, but it was decided by @simskij and @jnsgruk (see [#49 (comment)](https://github.com/canonical/charm-relation-interfaces/pull/49#issuecomment-1469474761)) that this would be the design. The reasoning is IIRC: for those who'd rather read or use jsonschema (the de-facto portable standard, rather than pydantic), it'd be better to be able to see it in-repo, instead of having to generate it manually or dig through build artifacts to find them.
> > If you wish to re-open the discussion on that one, fine by me but not here :)
> 
> @simskij's comment mentions that we should "have a CI step that generates the json schema", that's not what we have here.

Well, both really. A checked-in schema, that the CI then validates against.

**Comment by gruyaume** [comment]
> 
All right, I added them.

I feel like the workflow could be improved. Why ask authors to auto-generate json schemas if we end up doing the same in the CI? It feels like doing your tax returns (If you already know how much I owe, why do I have to tell you?)

**Comment by simskij** [comment]
> > 
> 
> All right, I added them.
> 
> I feel like the workflow could be improved. Why ask authors to auto-generate json schemas if we end up doing the same in the CI? It feels like doing your tax returns (If you already know how much I owe, why do I have to tell you?)

You have a point. The idea (I think) was to make sure it generates the same schema on an external machine, but it could very well be false safety/overengineering.

**Pull request merged**
