### PR TITLE
Updates json schemas

### PR DESCRIPTION
**Pull request by saltiyazan**
- Adds `Required` keyword in the schema to require specific auth modes to be passed.
- Changes `url` to list of `urls` in the requirer's schema.

### CODE REVIEW

**Comment by saltiyazan** [comment]
Hi @simskij @jnsgruk 
It seems like [This PR](https://github.com/canonical/charm-relation-interfaces/pull/24) has been forgotten :) 
Now when I was checking I closed it by accident, as I wasn't able to reopen it I just created this new PR with the same content, and with some minor updates to schemas (as in the lib)

**Comment by simskij** [comment]
No, we closed it because we don't want to set additionalProperties to false, as that will prevent incremental expansion of the supported auth modes without breaking backward compatibility.

**Comment by saltiyazan** [comment]
> No, we closed it because we don't want to set additionalProperties to false, as that will prevent incremental expansion of the supported auth modes without breaking backward compatibility.

Okay, I get it, for some reason I don't see that on Github. Then I assume I should close this one as well?

**Comment by saltiyazan** [comment]
> No, we closed it because we don't want to set additionalProperties to false, as that will prevent incremental expansion of the supported auth modes without breaking backward compatibility.

Btw, it doesn't set `additionalProperties` to false (that comment was addressed in the linked PR, and here as well)  :) So please take a look whenever you have some time.

**Review by simskij — APPROVED** [review]

**Review by jnsgruk — APPROVED** [review]

**Pull request merged**
